language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1
  - nightly

jobs:
  allow_failures:
    - julia: nightly
    - os: windows
  fast_finish: true
  include:
    - stage: "Documentation"
      julia: 1
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); 
                                    Pkg.instantiate()'
        - julia --project=docs/ --color=yes docs/make.jl
      name: "HTML"
      after_success: skip

notifications:
  email: false

codecov: true
